### ISSUE TITLE
Effect input is mic but no line in

### ISSUE THREAD

**Issue by SandeepJagdev** [TobiasVanDyk/Audio-Effects-Preamp-VS1053b#1]
Hello I uploaded your code to Arduino but I found problem that vs1053 accept input from mic but not line in please help

**Comment by TobiasVanDyk** [comment]
Oops I missed this - VLSI coded their DSP for a mono input only unfortunately = if you look at the [**diagram here**](https://www.instructables.com/Audio-Effects-Preamp-With-VS1053b/) it is shown as a mono input. It is possible to re-write it for stereo but the maximum delay times will then be halved.

**Comment by TobiasVanDyk** [comment]
Closed as based on VLSI code
